  SELECT * FROM TB_ACCOUNTS;
  SELECT * FROM TB_POLICY_DETAILS;
  SELECT * FROM TB_POLICY_HOLDER_DETAILS;
--TRUNCATE TB_ACCOUNTS;
--TRUNCATE TB_POLICY_DETAILS;
--TRUNCATE TB_POLICY_HOLDER_DETAILS;
--DELETE FROM TB_ACCOUNTS WHERE ID = 'ID0001P';
--DELETE FROM TB_POLICY_DETAILS WHERE CUST_ID = '000101REVC';
--DELETE FROM TB_POLICY_HOLDER_DETAILS WHERE CUST_ID = '000101REVC';
