  CREATE TABLE TOUR_DETAILS
      (
        TOUR_PLACE     CHAR(15) NOT NULL
       ,TOUR_GUIDE     CHAR(10)
       ,LANGUAGE       CHAR(03) NOT NULL
       ,TOUR_DATE      DATE     NOT NULL
       ,GROUP_SIZE     INT      NOT NULL
       ,PRICE_PER_HEAD INT      NOT NULL

       ,PRIMARY KEY(TOUR_PLACE)
       ,CHECK (LANGUAGE IN ('TAM','ENG'))
       ) IN ARI011DB.ARI011TS;

  CREATE UNIQUE INDEX TOUR_DETAILS_IDX ON TOUR_DETAILS(TOUR_PLACE);

  SELECT * FROM TOUR_DETAILS;