  CREATE TABLE SEASON_DISCOUNT
      (
        TOUR_PLACE     CHAR(15) NOT NULL
       ,FINAL_PRICE    INT      NOT NULL
       ,GUIDE          CHAR(10)
       ,DISCOUNT       INT      NOT NULL
       ,DATE           DATE     NOT NULL
       ,GROUP_DISCOUNT INT      NOT NULL

       ,PRIMARY KEY(TOUR_PLACE)
       ) IN ARI011DB.ARI011TS;

  CREATE UNIQUE INDEX SEASON_DISCOUNT_IDX
      ON SEASON_DISCOUNT(TOUR_PLACE);

  SELECT * FROM SEASON_DISCOUNT