  SELECT A.TOUR_PLACE,
         A.TOUR_GUIDE,
         A.LANGUAGE,
         A.TOUR_DATE,
         A.GROUP_SIZE,
         B.GROUP_DISCOUNT
    FROM TOUR_DETAILS A
    LEFT OUTER JOIN SEASON_DISCOUNT B
      ON A.TOUR_PLACE = B.TOUR_PLACE
    WHERE LANGUAGE = 'ENG' AND
      GROUP_SIZE > 10
    ORDER BY TOUR_PLACE;