  SELECT * FROM SEASON_DISCOUNT;
  SELECT LOWER(TOUR_PLACE) AS TOUR_PLACE,
         FINAL_PRICE,
         LOWER(GUIDE) AS GUIDE,
         DISCOUNT,
         DATE,
         GROUP_DISCOUNT
    FROM SEASON_DISCOUNT
    WHERE DISCOUNT <= 20;